[project]
name = "chronos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dashscope==1.20.3",
    "openai==1.58.1",
    "scikit-learn==1.6.0",
    "tilse==0.2.1",
    "tqdm==4.66.4",
    "transformers==4.47.1",
]
